[package]
name = "qrism"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
lru = "0.14.0"
nalgebra = "0.33.2"
num-traits = "0.2.19"
proptest = "1.6.0"
rand = "0.9.0"
rqrr = "0.9.3"

[dev-dependencies]
test-case = "3.3.1"
